### PR TITLE
Add Normalize as dependency

### PR DESCRIPTION
**Pull request by rafaell-lycan**
This PR will fix the issue #28 

**Main changes:**
- Update Normalize version to 3.0.3;
- Add Grunt Copy and Rename tasks to move normalize.css and rename to _normalize.scss;
- Add a postinstall script to run bower install command
- Update ignored files

**Why use Normalize as a dependency with Bower?**
- When we need to get the latest version of normalize, just set the current version on bower or, define to get always the last one.

### CODE REVIEW

**Comment by WhatsNewSaes** [comment]
getting some errors when i run `npm install`

Failed at the Skeleton-Sass@2.0.4 postinstall script 'bower install'

haven't had time to look into it, but I'm wondering if it has to do with being on OSX 10.11

**Comment by rafaell-lycan** [comment]
Humm... @WhatsNewSaes did u have bower installed?

**Comment by WhatsNewSaes** [comment]
yeah, v 1.6.5

**Comment by rafaell-lycan** [comment]
I'll try to simulate this error.

**Comment by rafaell-lycan** [comment]
@WhatsNewSaes I resolved the conflicts, but I cannot simulate the problem with bower. Could you try it again?

**Comment by WhatsNewSaes** [comment]
decided against downloading it as a dependancy. thanks though!

**Pull request closed without merging**
