### PR TITLE
Add bower

### PR DESCRIPTION
**Pull request by benhinchley**
Created the `bower.json` file and added all necessary parts to make it work as a bower package. Though after checking the bower package repository there is already a package called [skeleton-sass](https://github.com/atomicpages/skeleton-sass), so we might need to change the name to `skeleton-scss` or something

### CODE REVIEW

**Comment by benhinchley** [comment]
@whatsnewsaes also sorry for all the other random commits in there, couldn't figure out how to remove them from this PR

**Comment by whatsnewsaes** [comment]
Very Cool!

I wasn't really following the whole variable / different sass file / adding before import on issue #10 .

Adding !default will make it so that any other variable with the same name will automatically overwrite the !default variable. -- is that all we're trying to achieve here?

**Comment by benhinchley** [comment]
Yeah exactly, any variable with the same name before the `@import 'skeleton'` statement, with the same name will override the !default variables, otherwise the !default variables will stay.

**Comment by whatsnewsaes** [comment]
And that's something specific to Sass - correct? Less doesn't have that functionality that I'm aware of. 

I do like this, but I'm hesitant just for consistency reasons between the less/sass version. Let me think it over

**Comment by benhinchley** [comment]
Yes I believe it is sass specific, as the less docs say you should just redefine the variables after the import statement as shown and described here [less default variables](http://lesscss.org/features/#variables-feature-default-variables)

**Comment by whatsnewsaes** [comment]
Let's hold on that for the moment. I'll be glad to pull in bower right now tho. See update to your PR

**Comment by benhinchley** [comment]
Okay then, thats fine. Well yeah lets get bower working and we can work on adding the other features later. imo though moving forward it is probably going to be more difficult to keep your sass and less versions the same, due to the way the two preprocessors manage various things.

**Pull request merged**
