### PR TITLE
Fix column width / offset percents

### PR DESCRIPTION
**Pull request by lancepadgett**
I noticed they weren't exactly the same as the Get Skeleton file. This should make the percentages match.

### CODE REVIEW

**Comment by benhinchley** [comment]
@lancepadgett I hope you don't mind but I have updated my PR #6, to use your grid math, to make it easier to merge.

**Comment by lancepadgett** [comment]
@benhinchley :+1: I don't mind at all. Oh, and good idea to write it in a function.

**Comment by benhinchley** [comment]
@lancepadgett yeah I figured making it a function, would make it easier to change in the future

**Comment by whatsnewsaes** [comment]
Thanks guys. I got these changes in @benhinchley update

**Pull request closed without merging**
