### PR TITLE
Include Normalize, fix #28

### LINKED ISSUE #28: Include Normalize
Include Normalize and @import into the skeleton file.

### PR DESCRIPTION
**Pull request by dirtycoder**

### CODE REVIEW

**Comment by rafaell-lycan** [comment]
Hey @dirtycoder  I have done that too. But using bower to get the normalize file.

**Comment by dirtycoder** [comment]
@rafaell-lycan Nice! I just forgot about bower, heh. Your version is probably better. :)
This way, normalize comments will be preserved after the compilation?

**Comment by rafaell-lycan** [comment]
Unfortunately no, but if @WhatsNewSaes allow me, I could do a compile task to remove then. However isn't necessary.

**Comment by dirtycoder** [comment]
I think the comments are a nice thing to have, and somewhat follows the "inplace-documentation" already present Skeleton.

**Comment by rafaell-lycan** [comment]
Yeap, but if you think that we'll compile and minify the CSS doesn't matter. :ghost:

**Comment by dirtycoder** [comment]
For me, it does matter. It *really* matter. If we go to the "the ends justify the means" and consequentialism path, a lot of things can go wrong.

Let's see for example the way Bootstrap handle it:
https://github.com/twbs/bootstrap/pull/11176

PS: By no means I wanted to be rude, but if I sound like it, I ask you to forgive me upfront, I don't have a proper command of the english language.

**Comment by WhatsNewSaes** [comment]
What is the benefit to having it as a dev dependency as opposed to downloading it within the project scss folder?

**Comment by dirtycoder** [comment]
Hey @WhatsNewSaes, I think the single benefit of having normalize as a dependency in bower is that it's is "easier" to upgrade.

But keeping in mind the pace of release of normalize.css ([here](https://github.com/necolas/normalize.css/releases)) I think we are better off leaving it as a file inside project scss folder.

As I don't like the idea of having it as a dev dependency, which is ultimately not, I prefer the way proposed in this PR.

**Comment by WhatsNewSaes** [comment]
Thanks @dirtycoder, I'm kinda leaning that way too. I'll give it a day or two to think it over, but we'll probably end up going this rout.

Thanks guys!

**Comment by dirtycoder** [comment]
@WhatsNewSaes I'll update this PR to resolve the conflicts later today.

**Comment by dirtycoder** [comment]
@WhatsNewSaes I'm not sure if normalize should be in the base folder, what do you think?

**Pull request merged**
