### PR TITLE
Update to 2.0.4

### PR DESCRIPTION
**Pull request by benhinchley**
Updated this file to 2.0.4, and also fixed up the grid math according to pr #5

### CODE REVIEW

**Comment by whatsnewsaes** [comment]
@benhinchley at first glance this looks great. I'll dig into a little further later this evening to test everything out on my end. Much appreciated!

**Comment by benhinchley** [comment]
@whatsnewsaes all good, have also added a .editorconfig file, to help keep the code style consistent.

**Comment by benhinchley** [comment]
@whatsnewsaes just updated my PR according to the changes you made in #9

**Comment by whatsnewsaes** [comment]
got it

**Pull request closed without merging**
